package com.adventure.enums;

public enum NotificationType {
    BOOKING_CONFIRMED, BOOKING_CANCELLED, PAYMENT_SUCCESS,
    PAYMENT_FAILED, TREK_REMINDER, REVIEW_REQUEST,
    COUPON_OFFER, SYSTEM_ALERT
}
